# Generated by Django 5.2.5 on 2025-09-12 05:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('inventory', '0002_remove_product_supplier_delete_movement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('stock_min', models.PositiveIntegerField(verbose_name='Stock minimo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
