# Generated by Django 5.2.5 on 2025-09-19 01:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_producto_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario_Productos',
                'verbose_name_plural': 'Inventario_Productos',
            },
        ),
    ]
