# Generated by Django 5.2.5 on 2025-09-19 01:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventario_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inventario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Registro_Inventario',
                'verbose_name_plural': 'Registro_Inventarios',
            },
        ),
    ]
