# Generated by Django 5.2.5 on 2025-09-19 01:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_registro_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_inventario',
            old_name='cantidad',
            new_name='cantidad_nueva',
        ),
        migrations.RenameField(
            model_name='registro_inventario',
            old_name='fecha',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='registro_inventario',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='registro_inventario',
            name='cantidad_anterior',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior'),
        ),
        migrations.AddField(
            model_name='registro_inventario',
            name='inventario_producto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventario_producto', verbose_name='Producto'),
        ),
    ]
