# Generated by Django 5.2.5 on 2025-09-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_cantidad_registro_inventario_cantidad_nueva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/inventory/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='registro_inventario',
            name='comentarios',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Comentarios'),
        ),
    ]
