# Generated by Django 5.2.5 on 2025-09-22 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_producto_imagen_registro_inventario_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_producto', to='inventory.producto', verbose_name='Producto'),
        ),
    ]
