# Generated by Django 5.2.5 on 2025-09-22 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventario_producto_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto',
            name='producto_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventory.producto', verbose_name='Producto'),
        ),
    ]
