# Generated by Django 5.2.5 on 2025-09-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventario_producto_producto_id'),
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_producto',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio', verbose_name='Negocio'),
        ),
    ]
