# Generated by Django 5.2.5 on 2025-09-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventario_producto_negocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['modificado'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
