# Generated by Django 5.2.5 on 2025-10-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Medida')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Medida de Inventario',
                'verbose_name_plural': 'Medidas de Inventario',
            },
        ),
    ]
