# Generated by Django 5.2.5 on 2025-10-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_medidas_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medidas_inventario', verbose_name='Medida'),
        ),
    ]
