# Generated by Django 5.2.5 on 2025-10-23 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_producto_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidas_inventario',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='medidas_inventario',
            name='abreviatura',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AddField(
            model_name='medidas_inventario',
            name='permite_decimales',
            field=models.BooleanField(default=False, verbose_name='Permite Decimales'),
        ),
        migrations.AlterField(
            model_name='inventario_producto',
            name='cantidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_min',
            field=models.FloatField(default=0, verbose_name='Stock minimo'),
        ),
        migrations.AlterField(
            model_name='registro_inventario',
            name='cantidad_anterior',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior'),
        ),
        migrations.AlterField(
            model_name='registro_inventario',
            name='cantidad_nueva',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
