# Generated by Django 5.2.5 on 2025-10-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_medidas_inventario_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidas_inventario',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Abreviatura'),
        ),
    ]
