# Generated by Django 5.2.5 on 2025-10-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_medidas_inventario_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidas_inventario',
            name='abreviatura',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Abreviatura'),
        ),
    ]
