# Generated by Django 5.2.5 on 2025-10-24 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_medidas_inventario_abreviatura'),
        ('negocio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Inventario')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Inventario Activo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios_inventario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios_inventario_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por')),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Negocio Inventario',
                'verbose_name_plural': 'Negocios Inventario',
            },
        ),
        migrations.CreateModel(
            name='Registro_Negocio_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_nueva', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Nueva')),
                ('cantidad_anterior', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Anterior')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('comentarios', models.TextField(blank=True, max_length=255, null=True, verbose_name='Comentarios')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_negocio_inventario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('negocio_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='inventory.negocio_inventario', verbose_name='Negocio Inventario')),
            ],
            options={
                'verbose_name': 'Registro Negocio Inventario',
                'verbose_name_plural': 'Registros Negocio Inventario',
            },
        ),
    ]
