# Generated by Django 5.2.5 on 2025-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_negocio_inventario_registro_negocio_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='motivo_movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Motivo')),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de Movimiento',
                'verbose_name_plural': 'Motivos de Movimiento',
            },
        ),
    ]
