# Generated by Django 5.2.5 on 2025-11-24 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_ordendecompra_estatus'),
        ('inventory', '0019_motivo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_inventario',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.ordendecompra'),
        ),
    ]
