# Generated by Django 5.2.5 on 2025-11-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_registro_inventario_orden_compra'),
        ('negocio', '0002_alter_negocio_logo_alter_negocio_regimen_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio_inventario',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='negocio_inventario',
            name='negocio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio', verbose_name='Negocio'),
        ),
    ]
