# Generated by Django 5.2.5 on 2025-11-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_negocio_inventario_producto_and_more'),
        ('negocio', '0002_alter_negocio_logo_alter_negocio_regimen_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio_inventario',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio', verbose_name='Negocio'),
        ),
    ]
