# Generated by Django 5.2.5 on 2025-09-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_inventario_producto_negocio'),
        ('negocio', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_orden', models.CharField(max_length=20, verbose_name='Número de orden')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio', verbose_name='Negocio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
                ('usuario_autorizo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario autorizó')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
                ('usuario_solicito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitó')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
            },
        ),
        migrations.CreateModel(
            name='ProductoEnOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='compra.ordendecompra', verbose_name='Orden de compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producto', verbose_name='Producto')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_en_orden_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_en_orden_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Producto en orden',
                'verbose_name_plural': 'Productos en orden',
            },
        ),
    ]
