# Generated by Django 5.2.5 on 2025-11-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoenorden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal'),
        ),
    ]
