# Generated by Django 5.2.5 on 2025-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_productoenorden_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estatus'),
        ),
    ]
