# Generated by Django 5.2.5 on 2025-09-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_fiscal', models.CharField(max_length=100, verbose_name='Nombre fiscal')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocio/logos/', verbose_name='Logo')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('regimen_fiscal', models.CharField(max_length=100, verbose_name='Régimen fiscal')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código postal')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='ContactoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_negocio_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_negocio_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='negocio.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Contacto del negocio',
                'verbose_name_plural': 'Contactos del negocio',
            },
        ),
    ]
