# Generated by Django 5.2.5 on 2025-10-30 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
        ('proveedores', '0007_alter_proveedor_caratula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/negocio/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='regimen_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='proveedores.regimenfiscal', verbose_name='Régimen fiscal'),
        ),
    ]
