# Generated by Django 5.2.5 on 2025-09-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero_de_cuenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de cuenta')),
                ('opinion_de_cumplimiento', models.FileField(blank=True, null=True, upload_to='proveedores/opiniones_de_cumplimiento/', verbose_name='Opinion de cumplimiento')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón social')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('regimen_fiscal', models.CharField(max_length=100, verbose_name='Regimen fiscal')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código postal')),
                ('caratula', models.FileField(blank=True, null=True, upload_to='proveedores/caratulas/', verbose_name='Caratula')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_proveedor_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_proveedor_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contacto Proveedor',
                'verbose_name_plural': 'Contactos Proveedores',
            },
        ),
    ]
