# Generated by Django 5.2.5 on 2025-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=3, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Régimen Fiscal',
                'verbose_name_plural': 'Régimenes Fiscales',
            },
        ),
    ]
