# Generated by Django 5.2.5 on 2025-09-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_regimenfiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimenfiscal',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='Código'),
        ),
    ]
