# Generated by Django 5.2.5 on 2025-09-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_regimenfiscal_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='regimen_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.regimenfiscal', verbose_name='Régimen fiscal'),
        ),
    ]
