# Generated by Django 5.2.5 on 2025-10-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_contactoproveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numero_de_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de cuenta'),
        ),
    ]
