# Generated by Django 5.2.5 on 2025-10-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_alter_proveedor_numero_de_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='caratula',
            field=models.FileField(blank=True, null=True, upload_to='pdf/proveedores/caratulas/', verbose_name='Caratula'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='opinion_de_cumplimiento',
            field=models.FileField(blank=True, null=True, upload_to='pdf/proveedores/opiniones_de_cumplimiento/', verbose_name='Opinion de cumplimiento'),
        ),
    ]
