# Generated by Django 5.2.5 on 2025-10-31 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_motivo_movimiento'),
        ('proveedores', '0007_alter_proveedor_caratula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_proveedor', to='inventory.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('usuario_creo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_proveedor_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('usuario_modifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_proveedor_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Producto Proveedor',
                'verbose_name_plural': 'Productos Proveedores',
            },
        ),
    ]
