# Generated by Django 5.2.5 on 2025-11-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_motivo_movimiento'),
        ('proveedores', '0008_productosproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.producto', verbose_name='Producto'),
        ),
    ]
